/**
 * SoCoABE Central Configuration File
 * Paper 1 version: Removed FixedSTP, NetworkModule, Social Learning, Testing.
 */

// ============================================================
// DISTRIBUTION REGISTRY
// ============================================================
// All agent-initialization distributions live in JSON files.
// Edit these files directly to change agent behavior.
// Run landscape_init/ scripts only when changing the spatial grid.
//
// TRAIT DISTRIBUTIONS (preferences, resources, adherence, risk):
//   File: config/tables/traits/agent_traits.json
//   Structure: behavioral_type -> {preferences, resources, adherence, riskTolerance}
//   Consumed by: owner.js -> agent constructor -> sample_my_traits()
//
// ACTIVITY DISTRIBUTIONS (Dirichlet alpha vectors per type x phase):
//   File: config/tables/activities/activity_distributions.json
//   Structure: behavioral_type -> phase -> {options:[], alpha:[]}
//   Consumed by: agent constructor -> apply_guideline_blend() -> agent.activity_table
//   NOTE: These are own_ideal distributions. The GUIDELINE (below)
//         is blended in at init time using agent's adherence score.
//
// PARAMETERS (fixed silvicultural params per activity x type):
//   File: config/tables/params/parameter_distributions.json
//   Structure: activity -> behavioral_type -> {param: value, ...}
//   Consumed by: owner.js -> agent.parameter_table -> select_parameters.js
//
// PROFILES (targetDBH thresholds, plenter equilibrium curves):
//   Files: config/tables/profiles/targetDBH_profiles.json
//          config/tables/profiles/plenter_profiles.json
//   Consumed by: owner.js -> agent.targetDBH_profiles_table / plenter_profiles_table
//
// SPECIES STRATEGIES (thinning selectivity weights, planting mix):
//   File: config/tables/species/species_strategies.json
//   Structure: THINNING_WEIGHTS -> type -> condition -> {species: weight[0-1]}
//              PLANTING_CONFIG -> type -> {n_species, weights:{species: prob}}
//   Consumed by: SpeciesStrategies.get_thinning_weights() / get_planting_mix()
//   NOTE: All weight values MUST be in [0, 1]. iLand C++ clamps them.
//         Species with weight > 0.5 receive tending protection.
//         Paper 1 uses same weights for tending/thinning/shelterwood.
//
// GUIDELINE (institutional activity distributions):
//   Defined below in GUIDELINE section.
//   Accessed at runtime via socoabe.institution.guideline
//   Blended with own_ideal at agent init. Paper 1: guideline = MF own_ideal.
//
// ES DEMAND (ecosystem service demand weights):
//   Defined below in ES_DEMAND section.
//   Accessed at runtime via socoabe.institution.es_demand
//   Paper 1: post-processing only, no runtime effect.
//
// GRID & LANDSCAPE (stand allocation, agent sizing):
//   Generated by: landscape_init/ R scripts (separate from SOCO)
//   Output: stand_files/agent_table_*.csv, init/*.asc, init/*.csv
//   Only re-run when changing spatial layout.
// ============================================================

if (typeof SoCoABE_CONFIG === 'undefined') {
    var SoCoABE_CONFIG = {
        csv_path: "./abe/stand_files/agent_table_high_shuffled-false.csv",
        core_abe_agent_type: 'socoabe_controller',
        warmupPeriod: 0,

        // Warming period: Activities ARE performed but NOT recorded
        WARMING: {
            ENABLED: false,
            DURATION: 10,
        },

        // Console logging control
        SOCO_LOG: {
            ENABLED: false,
            ENABLED_DURING_WARMING: false,
            LOG_ACTIVITIES: false,
            LOG_AGENT_CYCLES: false,
            LOG_DECISIONS: false,
            LOG_PERCEPTION: false,
        },

        LOGGING: {
            DEBUG: true,   // true during dev; false for cluster runs
            WARN: true
        },

        // Management control: set to false to disable SoCoABE cognitive system
        // (no-management control — forest grows with disturbances only)
        MANAGEMENT_ENABLED: true,

        // Disturbance control: suppress all disturbances before this year.
        // Both wind and bark beetle XML modules remain enabled but are
        // neutered via JS API until this year, then restored to XML defaults.
        DISTURBANCE_START_YEAR: 1,

        // Bark beetle outbreak scenario (on top of XML baseline)
        // Default outbreak window: years 200-300 (treatment period)
        // Timeline: 0-100 warmup | 100-200 control (no BB) | 200-300 treatment
        // Overridable via user.outbreak_start_year / user.outbreak_end_year CLI params
        BARK_BEETLE: {
            ENABLED: true,
            OUTBREAK_YEARS: [
                200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210,
                211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
                221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
                231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
                241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
                251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
                261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
                271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
                281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
                291, 292, 293, 294, 295, 296, 297, 298, 299, 300],
            OUTBREAK_PROBABILITY: 0.001,
            BASELINE_PROBABILITY: 0.00001,
            LOG_ENABLED: true
        },

        // Static ecosystem service demand (post-processing only in Paper 1)
        ES_DEMAND: { Production: 0.4, Biodiversity: 0.3, CO2: 0.3 },

        // Behavioral types (Paper 1 - Sotirov)
        BEHAVIORAL_TYPES: ["MF", "OP", "TR", "PA", "EN"],
        SMALL_PRIVATE_SPLIT: { TR: 0.40, PA: 0.30, EN: 0.30 },

        // Budget system (Paper 1 - resource-constrained planning)
        BUDGET: {
            POINTS_PER_STAND_PER_DECADE: 3,   // budget = resources * n_ALL_stands * this
            MAX_CARRYOVER_FACTOR: 2.0,
            ALLOW_DEBT: true,
            MAX_DEBT_FACTOR: 0.5,
            DISTURBANCE_ENVELOPE: 8,           // salvage clearcut cost = max(0, envelope - extraction_paid) + planting
            BUDGET_STRETCH: {
                REFERENCE_PRESSURE: 2.0,       // pts/stand/decade at which stretch=1.0 (≈ MF level)
                MAX_STRETCH: 3.0               // cap to prevent absurd intervals
            }
        },

        // Phase windows with start-by cutoffs (can't start new activity after start_by)
        PHASES: {
            Planting: { start: 0, end: 5, start_by: 5 },
            Tending: { start: 6, end: 20, start_by: 18 },
            Thinning: { start: 21, end: 79, start_by: 60 },
            Harvesting: { start: 80, end: 999, start_by: 999 }
        },

        // Structural thresholds — loaded from JSON in SOCO_main.load_all_configs()
        PHASE_THRESHOLDS: {},

        // Sustained yield: fraction of stands harvested per rotation-decade
        HARVEST_INTENSITY: { MF: 1.0, OP: 1.2, TR: 0.6, EN: 0.3, PA: 0.3 },
        HARVEST_ROTATION_DECADES: 8,

        // Institutional guideline (Paper 1: identical to MF own_ideal)
        GUIDELINE: {
            period: { start: 0, end: 999 },
            Harvesting: {
                options: ["shelterwood", "targetDBH", "clearcut", "plenter_harvest", "femel"],
                alpha: [4, 3, 0, 3, 5]
            },
            Thinning: {
                options: ["selectiveThinning", "fromBelow", "plenter_thinning", "noManagement"],
                alpha: [5, 3, 2, 0.5]
            },
            Tending: {
                options: ["tending", "noManagement"],
                alpha: [9, 1]
            },
            Planting: {
                options: ["planting", "noManagement"],
                alpha: [9, 1]
            }
        },

        // THINNING_WEIGHTS and PLANTING_CONFIG are loaded from
        // config/tables/species/species_strategies.json at init time (SOCO_main.js).
        // They are injected into this config object at runtime.

        // "age" = age-based phases (current). "structural" = topH/DBH/volume phases.
        PHASE_ENGINE: "structural",

        // Species selectivity mode
        // 'static': use speciesSelectivity from STP options as-is (current behavior)
        // 'wet_dynamic': classify stand into WET type, compute owner-specific target
        SPECIES_SELECTIVITY_MODE: 'wet_dynamic',

        // WET reference target compositions (midpoints from WET 2024)
        WET_TARGETS: {
            'b': { fasy: 0.60, qusp: 0.15, acsp: 0.10, piab: 0.10, rest: 0.05 },
            'e': { qusp: 0.55, fasy: 0.15, cabe: 0.10, tico: 0.10, rest: 0.10 },
            'f': { piab: 0.50, fasy: 0.25, abal: 0.10, psme: 0.10, rest: 0.05 },
            't': { abal: 0.35, fasy: 0.25, piab: 0.15, qusp: 0.15, rest: 0.10 },
            'd': { psme: 0.55, fasy: 0.25, acsp: 0.10, rest: 0.10 },
            'k': { pisy: 0.60, fasy: 0.15, abal: 0.10, qusp: 0.10, rest: 0.05 },
            'h': { acsp: 0.25, frex: 0.20, qusp: 0.20, fasy: 0.15, rest: 0.20 },
            'j': { acsp: 0.25, qusp: 0.25, cabe: 0.15, tico: 0.15, rest: 0.20 }
        },

        // Owner-type species params
        // c: 0=WET target, 1=current composition, >1=amplify dominant, <0=more diverse
        // intensity: 0=no regulation, 1=full
        OWNER_SPECIES_PARAMS: {
            'MF': { c: 0.0, intensity: 0.9 },
            'EN': { c: -0.2, intensity: 0.5 },
            'TR': { c: 0.7, intensity: 0.3 },
            'PA': { c: 0.0, intensity: 0.0 },
            'OP': { c: 1.3, intensity: 0.6 }
        },

        // Run without agent interventions
        NO_INTERVENTION: false,

        // Output file prefix for batch runs
        OUTPUT_PREFIX: "",

        // Data source paths (for documentation / programmatic access)
        DATA_SOURCES: {
            activities: 'tables/activities/activity_distributions.json',
            traits: 'tables/traits/agent_traits.json',
            parameters: 'tables/params/parameter_distributions.json',
            profiles_dbh: 'tables/profiles/targetDBH_profiles.json',
            profiles_pl: 'tables/profiles/plenter_profiles.json',
            species: 'tables/species/species_strategies.json',
            activity_costs: 'tables/budget/activity_costs.json',
            set_aside_rates: 'tables/budget/set_aside_rates.json',
            priority_weights: 'tables/budget/priority_weights.json'
        },

        MONITORING: {
            ML_LOG: true,
            DECADE_LOG: true,
            STAND_STATE_LOG: true,
            OUTPUT_FILES: {
                ML_ACTIVITY: "soco_ml_activities",
                DECADE_DECISIONS: "soco_decade_decisions",
                DECADE_SNAPSHOT: "soco_decade_snapshot",
                STAND_STATE: "soco_stand_state"
            }
        }
    };
}
this.SoCoABE_CONFIG = SoCoABE_CONFIG;
