/**
 * SoCoABE Central Configuration File
 * Paper 1 version: Removed FixedSTP, NetworkModule, Social Learning, Testing.
 */

// ============================================================
// DISTRIBUTION REGISTRY
// ============================================================
// All agent-initialization distributions live in JSON files.
// Edit these files directly to change agent behavior.
// Run landscape_init/ scripts only when changing the spatial grid.
//
// TRAIT DISTRIBUTIONS (preferences, resources, adherence, risk):
//   File: config/tables/traits/agent_traits.json
//   Structure: behavioral_type -> {preferences, resources, adherence, riskTolerance}
//   Consumed by: owner.js -> agent constructor -> sample_my_traits()
//
// ACTIVITY DISTRIBUTIONS (Dirichlet alpha vectors per type x phase):
//   File: config/tables/activities/activity_distributions.json
//   Structure: behavioral_type -> phase -> {options:[], alpha:[]}
//   Consumed by: agent constructor -> apply_guideline_blend() -> agent.activity_table
//   NOTE: These are own_ideal distributions. The GUIDELINE (below)
//         is blended in at init time using agent's adherence score.
//
// PARAMETERS (fixed silvicultural params per activity x type):
//   File: config/tables/params/parameter_distributions.json
//   Structure: activity -> behavioral_type -> {param: value, ...}
//   Consumed by: owner.js -> agent.parameter_table -> select_parameters.js
//
// PROFILES (targetDBH thresholds, plenter equilibrium curves):
//   Files: config/tables/profiles/targetDBH_profiles.json
//          config/tables/profiles/plenter_profiles.json
//   Consumed by: owner.js -> agent.targetDBH_profiles_table / plenter_profiles_table
//
// SPECIES STRATEGIES (thinning selectivity weights, planting mix):
//   File: config/tables/species/species_strategies.json
//   Structure: THINNING_WEIGHTS -> type -> condition -> {species: weight[0-1]}
//              PLANTING_CONFIG -> type -> {n_species, weights:{species: prob}}
//   Consumed by: SpeciesStrategies.get_thinning_weights() / get_planting_mix()
//   NOTE: All weight values MUST be in [0, 1]. iLand C++ clamps them.
//         Species with weight > 0.5 receive tending protection.
//         Paper 1 uses same weights for tending/thinning/shelterwood.
//
// GUIDELINE (institutional activity distributions):
//   Defined below in GUIDELINE section.
//   Accessed at runtime via socoabe.institution.guideline
//   Blended with own_ideal at agent init. Paper 1: guideline = MF own_ideal.
//
// ES DEMAND (ecosystem service demand weights):
//   Defined below in ES_DEMAND section.
//   Accessed at runtime via socoabe.institution.es_demand
//   Paper 1: post-processing only, no runtime effect.
//
// GRID & LANDSCAPE (stand allocation, agent sizing):
//   Generated by: landscape_init/ R scripts (separate from SOCO)
//   Output: stand_files/agent_table_*.csv, init/*.asc, init/*.csv
//   Only re-run when changing spatial layout.
// ============================================================

if (typeof SoCoABE_CONFIG === 'undefined') {
    var SoCoABE_CONFIG = {
        csv_path: "./abe/stand_files/agent_table_high_shuffled-false.csv",
        core_abe_agent_type: 'socoabe_controller',
        warmupPeriod: 0,

        // Warming period: Activities ARE performed but NOT recorded
        WARMING: {
            ENABLED: false,
            DURATION: 10,
        },

        // Console logging control
        SOCO_LOG: {
            ENABLED: false,
            ENABLED_DURING_WARMING: false,
            LOG_ACTIVITIES: false,
            LOG_AGENT_CYCLES: false,
            LOG_DECISIONS: false,
            LOG_PERCEPTION: false,
        },

        // Bark beetle outbreak scenario
        BARK_BEETLE: {
            ENABLED: true,
            OUTBREAK_YEARS: [15, 30],
            OUTBREAK_PROBABILITY: 0.05,
            BASELINE_PROBABILITY: 0.000685,
            LOG_ENABLED: true
        },

        // Static ecosystem service demand (post-processing only in Paper 1)
        ES_DEMAND: { Production: 0.4, Biodiversity: 0.3, CO2: 0.3 },

        // Behavioral types (Paper 1 - Sotirov)
        BEHAVIORAL_TYPES: ["MF", "OP", "TR", "PA", "EN"],
        SMALL_PRIVATE_SPLIT: { TR: 0.40, PA: 0.30, EN: 0.30 },

        // Institutional guideline (Paper 1: identical to MF own_ideal)
        GUIDELINE: {
            period: { start: 0, end: 999 },
            Harvesting: {
                options: ["shelterwood", "targetDBH", "clearcut", "plenter_harvest", "femel", "noManagement"],
                alpha: [4, 3, 0, 3, 5, 0]
            },
            Thinning: {
                options: ["selectiveThinning", "fromBelow", "plenter_thinning", "noManagement"],
                alpha: [5, 3, 2, 0]
            },
            Tending: {
                options: ["tending", "noManagement"],
                alpha: [8, 2]
            },
            Planting: {
                options: ["planting", "noManagement"],
                alpha: [9, 1]
            }
        },

        // THINNING_WEIGHTS and PLANTING_CONFIG are loaded from
        // config/tables/species/species_strategies.json at init time (SOCO_main.js).
        // They are injected into this config object at runtime.

        // Run without agent interventions
        NO_INTERVENTION: false,

        // Output file prefix for batch runs
        OUTPUT_PREFIX: "",

        // Data source paths (for documentation / programmatic access)
        DATA_SOURCES: {
            activities:   'tables/activities/activity_distributions.json',
            traits:       'tables/traits/agent_traits.json',
            parameters:   'tables/params/parameter_distributions.json',
            profiles_dbh: 'tables/profiles/targetDBH_profiles.json',
            profiles_pl:  'tables/profiles/plenter_profiles.json',
            species:      'tables/species/species_strategies.json'
        },

        MONITORING: {
            ENABLED: true,
            sample_size: 10,

            OUTPUT_FILES: {
                ML_ACTIVITY: "soco_ml_activities",
                SIMPLE_ACTIVITY: "soco_log_activities",
                HARVEST: "soco_log_harvest",
                DETAILED_STANDS: "soco_log_detailed_stands",
                AGGREGATED: "soco_log_aggregated_species",
                YEARLY_STRUCTURE: "soco_yearly_structure"
            },

            ML_ACTIVITY_LOG: true,
            SIMPLE_ACTIVITY_LOG: false,
            HARVEST_LOG: false,
            DETAILED_STAND_LOG: false,
            DETAILED_LOG_SAMPLE_SIZE: 10,
            AGGREGATED_LOG: false,
            YEARLY_STRUCTURE_LOG: true
        }
    };
}
this.SoCoABE_CONFIG = SoCoABE_CONFIG;
